name: noisy_app
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Dart SDK 범위 설정
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  noise_meter: ^5.0.2
  permission_handler: ^11.3.1
  audio_streamer: ^4.1.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # flutter_lints 버전 낮추기

flutter:
  uses-material-design: true
  assets:
      - assets/img.png



